version: "3.6"

services:
    whoami:
        image: traefik/whoami:v1.6.1
        deploy:
            mode: replicated
            replicas: 1
            labels:
                - traefik.enable=true
                - traefik.docker.network=lb_network
                - traefik.constraint-label=traefik-public
                - traefik.http.routers.whoami.rule=Path(`/whoami`)
                - traefik.http.services.whoami.loadbalancer.server.port=80
        networks:
            - lb_network

    registry:
        image: registry:2
        ports:
            - 5000:5000
        networks:
            - lb_network
        volumes:
            - registry:/var/lib/registry
        deploy:
            mode: replicated
            replicas: 1
            labels:
                - traefik.enable=true
                - traefik.docker.network=lb_network
                - traefik.constraint-label=traefik-public
                - traefik.http.routers.registry.rule=(Host(`registry.mydomain.com`) && PathPrefix(`/v2/`))
                - traefik.http.routers.registry.entrypoints=https
                - traefik.http.routers.registry.tls=true
                - traefik.http.routers.registry.tls.certresolver=le
                - traefik.http.services.registry.loadbalancer.server.port=5000

    agent:
        # The STS version is needed to work with Docker 0.0.26 (they changed the API!):
        # Docker 26 broke opening consoles of containers in the LTS Portainer versions
        # by removing an API without telling the Portainer guys. Well done, guys!
        # Because the scripts install the latest version of Docker, this bug hits.
        # The only available workaround is to use the ShortTerm Portainer 2.20.x
        # which also has the sts tag for ShortTermSupport. Nice, Love Docker...!
        # https://www.portainer.io/blog/portainer-and-docker-26
        # https://github.com/portainer/portainer/issues/11436
        image: portainer/agent:sts
        environment:
            # REQUIRED: Should be equal to the service name prefixed by "tasks." when
            # deployed inside an overlay network
            AGENT_CLUSTER_ADDR: tasks.swarm_agent
            # AGENT_PORT: 9001
            # LOG_LEVEL: debug
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
            - /var/lib/docker/volumes:/var/lib/docker/volumes
        networks:
            - agent_network
        deploy:
            mode: global
            placement:
                constraints: [node.platform.os == linux]

    portainer:
        # The STS version is needed to work with Docker 0.0.26 (they changed the API!):
        # Docker 26 broke opening consoles of containers in the LTS Portainer versions
        # by removing an API without telling the Portainer guys. Well done, guys!
        # Because the scripts install the latest version of Docker, this bug hits.
        # The only available workaround is to use the ShortTerm Portainer 2.20.x
        # which also has the sts tag for ShortTermSupport. Nice, Love Docker...!
        # https://github.com/portainer/portainer/issues/11436
        image: portainer/portainer-ce:sts
        command: -H tcp://tasks.swarm_agent:9001 --tlsskipverify
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
            - portainer:/data
        networks:
            - agent_network
            - lb_network
        deploy:
            mode: replicated
            replicas: 1
            labels:
                - traefik.enable=true
                - traefik.docker.network=lb_network
                - traefik.constraint-label=traefik-public
                - traefik.http.routers.portainer.rule=(Host(`portainer.mydomain.com`) && PathPrefix(`/`))
                - traefik.http.routers.portainer.entrypoints=https
                - traefik.http.routers.portainer.tls=true
                - traefik.http.routers.portainer.tls.certresolver=le
                - traefik.http.services.portainer.loadbalancer.server.port=9000

    traefik:
        # SwarmMode was changed to another setting in 3.1, so this needs updating for 3.1:
        image: traefik:v2.11
        ports:
            - target: 80
              published: 80
              protocol: tcp
              mode: host
            - target: 443
              published: 443
              protocol: tcp
              mode: host
        deploy:
            mode: global
            placement:
                constraints:
                    - node.role == manager
            restart_policy:
                condition: on-failure
                max_attempts: 3
                window: 120s
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock:ro
            - /var/log/traefik:/var/log/traefik:rw
            - registry:/data
        labels:
            - traefik.enable=true
            - traefik.http.routers.traefik.rule=Host(`traefik.mydomain.com`) && (PathPrefix(`/api`) || PathPrefix(`/dashboard`))
            - traefik.http.routers.api.service=api@internal
            - traefik.http.routers.traefik.entrypoints=https
            - traefik.http.routers.traefik.tls=true
            - traefik.http.routers.traefik.tls.certresolver=le
            - traefik.http.services.portainer.loadbalancer.server.port=8080
        command:
            - --providers.docker
            - --providers.docker.constraints=Label(`traefik.constraint-label`, `traefik-public`)
            - --providers.docker.exposedbydefault=false
            # SwarmMode was changed to another setting in 3.1, so this needs updating for 3.1:
            - --providers.docker.swarmmode
            - --entrypoints.http.address=:80
            - --entrypoints.https.address=:443
            - --serversTransport.insecureSkipVerify=true
            - --certificatesresolvers.le.acme.email=marcelo.ochoa@gmail.com
            - --certificatesresolvers.le.acme.storage=/data/acme.json
            - --certificatesresolvers.le.acme.tlschallenge=true
            - --entryPoints.http.forwardedHeaders.trustedIPs=127.0.0.1/32,10.1.22.0/24
            #- --entryPoints.https.forwardedHeaders.trustedIPs=127.0.0.1/32,129.144.0.0/12,129.144.0.0/12,129.213.0.0/16,130.35.0.0/16,132.145.0.0/16,134.70.0.0/16,138.1.0.0/16,140.204.0.0/16,140.91.0.0/16,147.154.0.0/16,192.157.18.0/23,192.29.0.0/16,192.69.118.0/23,198.181.48.0/21,199.195.6.0/23,205.147.88.0/21
            #- --log.level=INFO
            - --accesslog
            - --api
            - --api.dashboard
            - --log
            - --log.filePath=/var/log/traefik/traefik.log
            - --accesslog.filepath=/var/log/traefik/access.log
            - --accesslog.filters.statuscodes=200-499
            - --accesslog.filters.retryattempts
            - --accesslog.filters.minduration=10ms
        networks:
            - lb_network

volumes:
  registry:
    driver: s3fs
    name: "oci-registry-$DEPLOY_ID"
  portainer:
    driver: s3fs
    name: "oci-portainer-$DEPLOY_ID"

networks:
  # Use the previously created public network "traefik-public", shared with other
  # services that need to be publicly available via this Traefik
  lb_network:
    external: true
  agent_network:
    external: true
